name: waft-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - coverage
  - flake8
  - flake8-docstrings
  - interrogate
  - isort
  - mypy
  - pip
  - pip:
    - securecredentials
  - pudb
  - pycodestyle
  - pydocstyle
  - pylint
  - pytest
  - python=3.13
  - requests
  - textual
  - textual-dev
  - types-requests
